version: '3'
services:

  bff:
    container_name: bff-container
    build:
      context: ../../../helidon/helidon-quickstart-mp/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    container_name: redis-container
    image: redis:latest
    command: redis-server --appendonly yes --requirepass testpassword
    ports:
      - "6379:6379"
    environment:
      TZ: JST-9

  redisCommander:
    container_name: redis-commander-container
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOSTS: Redis:redis-container:6379:0:testpassword
      TZ: JST-9
    ports:
      - "8081:8081"
    depends_on:
      - redis